### ISSUE TITLE
Investigate runaway health check

### ISSUE THREAD

**Issue by ProofOfKeags** [Start9Labs/vaultwarden-wrapper#11]
Supposedly according to Start9Labs/embassy-os#867, there was a vaultwarden healthcheck that ran for 30hrs.

**Comment by chrisguida** [comment]
fixed in 172407bf2d4575c2b3dcad6f440ad2c35f56f9aa, please test @kn0wmad

**Comment by kn0wmad** [comment]
Have not witnessed this since first reported, will reopen if it pops up again
