### ISSUE TITLE
Rename Bitwarden to Vaultwarden

### ISSUE THREAD

**Issue by ProofOfKeags** [Start9Labs/vaultwarden-wrapper#8]
Would be nice to change the service ID to vaultwarden in the 0.2.x migration.

**Comment by chrisguida** [comment]
Probably should rename the repo and repoint the submodule as well

**Comment by chrisguida** [comment]
Sounds like we need a new vaultwarden service, since simply renaming it might break backwards compatibility with backups. Seems suboptimal to just leave the service id/image name/github repo with the old name though.

**Comment by MattDHill** [comment]
I'm not overly concerned about breaking backwards compatibility for backups. 0.3.0 cannot ingest 0.2.x backups anyway. In terms of the initial migration from 0.2.x, we can hard code an exception for bitwarden --> vaultwarden.
